#
# Copyright The NOMAD Authors.
#
# This file is part of NOMAD. See https://nomad-lab.eu for further info.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from typing import (
    TYPE_CHECKING,
)

from nomad.datamodel.data import (
    ArchiveSection,
    EntryData,
)
from nomad.datamodel.metainfo.basesections import PureSubstance
from nomad.datamodel.metainfo.basesections.v1 import (
    ElementalComposition,
)
from nomad.datamodel.metainfo.eln import (
    Sample,
    SampleID,
)
from nomad.metainfo import (
    Quantity,
    SchemaPackage,
    Section,
    SubSection,
)

if TYPE_CHECKING:
    from nomad.datamodel.datamodel import (
        EntryArchive,
    )
    from structlog.stdlib import (
        BoundLogger,
    )

m_package = SchemaPackage()


class Cathode(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln={
            "properties": {
                "order": [
                    "composition",
                    "mass",
                    "mass_active_material"
                ]
            }
        },
        label="Cathode",)
    mass = Quantity(
        type=float,
        description='Total mass of the cathode.',
        a_eln={
            "component": "NumberEditQuantity",
            "label": "Mass (Cathode)",
            "defaultDisplayUnit": "gram"
        },
        unit="gram",
    )
    mass_active_material = Quantity(
        type=float,
        description='Mass of the active material in the cathode.',
        a_eln={
            "component": "NumberEditQuantity",
            "label": "Mass of active material (Cathode)",
            "defaultDisplayUnit": "gram"
        },
        unit="gram",
    )
    elemental_composition = SubSection(
        section_def=ElementalComposition,
        repeats=True,
    )

    def normalize(self, archive: 'EntryArchive', logger: 'BoundLogger') -> None:
        '''
        The normalizer for the `Cathode` class.

        Args:
            archive (EntryArchive): The archive containing the section that is being
            normalized.
            logger (BoundLogger): A structlog logger.
        '''
        super().normalize(archive, logger)


class Electrolyte(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln={
            "properties": {
                "order": [
                    "mass",
                    "volume"
                ]
            }
        },
        label="Electrolyte",)
    mass = Quantity(
        type=float,
        description='Total mass of the electrolyte.',
        a_eln={
            "component": "NumberEditQuantity",
            "label": "Mass (Electrolyte)",
            "defaultDisplayUnit": "gram"
        },
        unit="gram",
    )
    volume = Quantity(
        type=float,
        description='Volume of the electrolyte.',
        a_eln={
            "component": "NumberEditQuantity",
            "label": "Volume (Electrolyte)",
            "defaultDisplayUnit": "milliliter"
        },
        unit="milliliter",
    )

    def normalize(self, archive: 'EntryArchive', logger: 'BoundLogger') -> None:
        '''
        The normalizer for the `Electrolyte` class.

        Args:
            archive (EntryArchive): The archive containing the section that is being
            normalized.
            logger (BoundLogger): A structlog logger.
        '''
        super().normalize(archive, logger)


class Separator(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln={
            "properties": {
                "order": [
                    "composition",
                    "thickness"
                ]
            }
        },
        label="Separator",)
    composition = Quantity(
        type=str,
        description='Material composition of the separator (e.g., PP/PE).',
        a_eln={
            "component": "StringEditQuantity",
            "label": "Composition (Separator)"
        },
    )
    thickness = Quantity(
        type=float,
        description='Thickness of the separator.',
        a_eln={
            "component": "NumberEditQuantity",
            "label": "Thickness (Separator)",
            "defaultDisplayUnit": "micrometer"
        },
        unit="micrometer",
    )

    def normalize(self, archive: 'EntryArchive', logger: 'BoundLogger') -> None:
        '''
        The normalizer for the `Separator` class.

        Args:
            archive (EntryArchive): The archive containing the section that is being
            normalized.
            logger (BoundLogger): A structlog logger.
        '''
        super().normalize(archive, logger)


class Substance(PureSubstance, EntryData, ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section()

    def normalize(self, archive: 'EntryArchive', logger: 'BoundLogger') -> None:
        '''
        The normalizer for the `Substance` class.

        Args:
            archive (EntryArchive): The archive containing the section that is being
            normalized.
            logger (BoundLogger): A structlog logger.
        '''
        super().normalize(archive, logger)


class Anode(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln={
            "properties": {
                "order": [
                    "material",
                    "mass"
                ]
            }
        },
        label="Anode",)
    # material = Quantity(
    #     type=Substance,
    #     description='Chemical composition or formula of the anode.',
    #     a_eln={
    #         "component": "ReferenceEditQuantity",
    #         "label": "Material (Anode)"
    #     },
    #     shape=["*"],
    # )

    material = SubSection(
        section_def=Substance,
        repeats=True
    )

    mass = Quantity(
        type=float,
        description='Total mass of the anode.',
        a_eln={
            "component": "NumberEditQuantity",
            "label": "Mass (Anode)",
            "defaultDisplayUnit": "gram"
        },
        unit="gram",
    )

    def normalize(self, archive: 'EntryArchive', logger: 'BoundLogger') -> None:
        '''
        The normalizer for the `Anode` class.

        Args:
            archive (EntryArchive): The archive containing the section that is being
            normalized.
            logger (BoundLogger): A structlog logger.
        '''
        super().normalize(archive, logger)

class Components(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
        a_eln={
            "properties": {
                "order": [
                    "anode",
                    "cathode",
                    "electrolyte",
                    "separator"
                ]
            }
        },
        label="Components",)
    anode = SubSection(
        section_def=Anode,
    )
    cathode = SubSection(
        section_def=Cathode,
    )
    electrolyte = SubSection(
        section_def=Electrolyte,
    )
    separator = SubSection(
        section_def=Separator,
    )

    def normalize(self, archive: 'EntryArchive', logger: 'BoundLogger') -> None:
        '''
        The normalizer for the `Components` class.

        Args:
            archive (EntryArchive): The archive containing the section that is being
            normalized.
            logger (BoundLogger): A structlog logger.
        '''
        super().normalize(archive, logger)


class BatterySample(Sample, ArchiveSection):
    '''
    Basic information about a battery sample including its components.
    '''
    m_def = Section(
        a_eln={
            "properties": {
                "order": [
                    "components",
                    "sample_identifiers"
                ]
            },
            "label": "Battery Sample",
            "entry_type": "Battery Sample"
        },
        label="Battery Sample",)
    components = SubSection(
        section_def=Components,
    )
    sample_identifiers = SubSection(
        section_def=SampleID,
    )

    def normalize(self, archive: 'EntryArchive', logger: 'BoundLogger') -> None:
        '''
        The normalizer for the `BatterySample` class.

        Args:
            archive (EntryArchive): The archive containing the section that is being
            normalized.
            logger (BoundLogger): A structlog logger.
        '''
        super().normalize(archive, logger)

m_package.__init_metainfo__()
